### ISSUE TITLE
Cannot View The Single Course Section

### ISSUE THREAD

**Issue by realswikarrr** [Sajani55/Content-Management-System#17]
![w](https://user-images.githubusercontent.com/80502023/118216470-470a9480-b493-11eb-9c31-7c1f9478bb16.PNG)

When I click the view button it should take me to the single course section but the code is just static and not doing anything !!

I think the route of the single course is not properly managed in App.js section. 

It is giving the error called Hook Issue, So I need this to be solved as quick as possible

**Comment by thebuggybug** [comment]
Hello, this issue has been fixed by adding `<Link to />` route path to **Single Course Page** and on button click the user redirect to Single Course Page
![image](https://user-images.githubusercontent.com/68284654/118265220-8c04ea00-b4d8-11eb-91fb-cdee598812f7.png)
![image](https://user-images.githubusercontent.com/68284654/118265292-a8088b80-b4d8-11eb-95de-4c3c36a39136.png)
![image](https://user-images.githubusercontent.com/68284654/118265246-945d2500-b4d8-11eb-884f-41a63d60f564.png)
