### ISSUE TITLE
Unmanaged Content grid due to backend code

### ISSUE THREAD

**Issue by thebuggybug** [Sajani55/Content-Management-System#18]
the content grid is not viewing as planned. It was fine until testing with only frontend code. It mis-behaved when backend was integrated to it. I think it can be solved by adding Backend code before `<MDBRow>` tag.
![2](https://user-images.githubusercontent.com/68284654/118216671-a9fc2b80-b493-11eb-8356-e81310ac08f0.PNG)
![1](https://user-images.githubusercontent.com/68284654/118216675-abc5ef00-b493-11eb-8d23-e38ceda77a1d.PNG)

**Comment by realswikarrr** [comment]
![image](https://user-images.githubusercontent.com/80502023/118356242-f2027780-b593-11eb-90e8-0f517e05bfd5.png)

The content grid have been managed successfully the problem was with the backend code which i fixed it !!

![image](https://user-images.githubusercontent.com/80502023/118356261-0cd4ec00-b594-11eb-8fe7-d8ac00ebca84.png)

Issue have been fixed and the content is in place
